- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.hgrc:
    ~/.inputrc:
    ~/.pythonrc:
    ~/.shell:
    ~/.tmux:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/.template:
    ~/.pylintrc:
    ~/.tig:
    ~/.tigrc:
    ~/.gdbinit: gdb-dashboard/.gdbinit
    ~/.gdbinit.d:
    ~/.config/bat/config: bat_config
    ~/.ripgreprc:
    ~/.zsh-complete: zsh/zsh-complete

- shell:
  - git update-submodules # after linking ~/.gitconfig
  -
    command:  (cd vim/bundle/YouCompleteMe/ && python install.py --all)
    description: Install YouCompleteMe
    quite: true
    stdout: true

  # install autojump
  -
    command:  (cd shell/plugins/autojump/ && ./install.py)
    description: Install Autojump
    quite: true
    stdout: true

  # generate tmuxline configure
  - vim -c 'Tmuxline airline' -c 'TmuxlineSnapshot! ~/.tmuxline.conf' -c 'quit'
  # generate promptline configure
  - vim -c 'PromptlineSnapshot! ~/.shell_prompt.sh airline' -c 'quit'

