- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.inputrc:
    ~/.pythonrc:
    ~/.shell:
    ~/.tmux:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/.template:
    ~/.pylintrc:

- shell:
  - git update-submodules # after linking ~/.gitconfig

  # generate tmuxline configure
  - vim -c 'Tmuxline airline' -c 'TmuxlineSnapshot! ~/.tmuxline.conf' -c 'quit'
  # generate promptline configure
  - vim -c 'PromptlineSnapshot! ~/.shell_prompt.sh airline' -c 'quit'

